<?php

namespace Tests\Feature;

use App\Models\{
    Bill,
    Product,
    Shop,
    User
};

use App\Enums\UserRole;

use Illuminate\Foundation\Testing\RefreshDatabase;

uses(RefreshDatabase::class);

beforeEach(function () {
    $this->admin = User::factory()->create([
        'role' => UserRole::ADMIN,
        'is_active' => true,
    ]);
    
    $this->cashier = User::factory()->create([
        'role' => UserRole::CASHIER,
        'is_active' => true,
    ]);
    
    $this->shop1 = Shop::factory()->create();
    $this->shop2 = Shop::factory()->create();
    
    $this->adminToken = auth('api')->tokenById($this->admin->id);
    $this->cashierToken = auth('api')->tokenById($this->cashier->id);
    
    $this->product1 = Product::factory()->create(['shop_id' => $this->shop1->id, 'price' => 10.00]);
    $this->product2 = Product::factory()->create(['shop_id' => $this->shop1->id, 'price' => 15.00]);
    $this->product_inactive = Product::factory()->create(['shop_id' => $this->shop1->id, 'is_active' => false]);
    $this->product_other_shop = Product::factory()->create(['shop_id' => $this->shop2->id]);
    $this->product_global = Product::factory()->create(['shop_id' => null, 'price' => 5.00]);
});

it('allows cashier to create a bill with active products in their shop context', function () {
    $response = $this->withHeader('Authorization', 'Bearer ' . $this->cashierToken)
        ->withHeader('X-Shop-ID', $this->shop1->hashed_id)
        ->postJson('/api/v1/bill/addbill', [
            'payment_method' => 1,
            'customer_name' => 'John Doe',
            'customer_phone' => '1234567890',
            'items' => [
                ['product_id' => $this->product1->hashed_id, 'quantity' => 2], // 20
                ['product_id' => $this->product_global->hashed_id, 'quantity' => 1], // 5
            ]
        ]);

    $response->assertStatus(201)
        ->assertJsonPath('data.customer_name', 'John Doe');
        
    $this->assertDatabaseHas('bills', [
        'shop_id' => $this->shop1->id,
        'cashier_id' => $this->cashier->id,
        'total' => 25.00,
        'bill_number' => 1, // generated by observer
    ]);
    
    $this->assertDatabaseHas('bill_items', [
        'product_id' => $this->product1->id,
        'quantity' => 2,
        'price_at_time_of_sale' => 10.00
    ]);
});

it('increments bill_number correctly per shop', function () {
    // Create first bill directly to trigger observer
    Bill::factory()->create(['shop_id' => $this->shop1->id]); // Should be 1
    
    $response = $this->withHeader('Authorization', 'Bearer ' . $this->adminToken)
        ->withHeader('X-Shop-ID', $this->shop1->hashed_id)
        ->postJson('/api/v1/bill/addbill', [
            'payment_method' => 1,
            'items' => [
                ['product_id' => $this->product1->hashed_id, 'quantity' => 1]
            ]
        ]);

    $response->assertStatus(201)
        ->assertJsonPath('data.bill_number', 2);
        
    // Shop 2 should still start at 1
    $response2 = $this->withHeader('Authorization', 'Bearer ' . $this->adminToken)
        ->withHeader('X-Shop-ID', $this->shop2->hashed_id)
        ->postJson('/api/v1/bill/addbill', [
            'payment_method' => 1,
            'items' => [
                ['product_id' => $this->product_global->hashed_id, 'quantity' => 1]
            ]
        ]);

    $response2->assertStatus(201)
        ->assertJsonPath('data.bill_number', 1);
});

it('prevents bill creation if product is inactive', function () {
    $response = $this->withHeader('Authorization', 'Bearer ' . $this->cashierToken)
        ->withHeader('X-Shop-ID', $this->shop1->hashed_id)
        ->postJson('/api/v1/bill/addbill', [
            'payment_method' => 1,
            'items' => [
                ['product_id' => $this->product_inactive->hashed_id, 'quantity' => 1],
            ]
        ]);

    $response->assertStatus(400)
        ->assertJsonPath('message', 'Product is inactive: ' . $this->product_inactive->name);
});

it('prevents bill creation if product belongs to another shop', function () {
    $response = $this->withHeader('Authorization', 'Bearer ' . $this->cashierToken)
        ->withHeader('X-Shop-ID', $this->shop1->hashed_id)
        ->postJson('/api/v1/bill/addbill', [
            'payment_method' => 1,
            'items' => [
                ['product_id' => $this->product_other_shop->hashed_id, 'quantity' => 1],
            ]
        ]);

    $response->assertStatus(400)
        ->assertJsonPath('message', 'Product does not belong to the active shop: ' . $this->product_other_shop->name);
});

it('lists bills for a specific shop context', function () {
    Bill::factory(3)->create(['shop_id' => $this->shop1->id]);
    Bill::factory(2)->create(['shop_id' => $this->shop2->id]);

    $response = $this->withHeader('Authorization', 'Bearer ' . $this->adminToken)
        ->withHeader('X-Shop-ID', $this->shop1->hashed_id)
        ->postJson('/api/v1/bill/getallbills');

    $response->assertStatus(200)
        ->assertJsonCount(3, 'data.data'); 
});

it('requires shop context to list bills unless admin', function () {
    $response = $this->withHeader('Authorization', 'Bearer ' . $this->cashierToken)
        ->postJson('/api/v1/bill/getallbills');

    $response->assertStatus(403)
        ->assertJsonPath('message', 'Shop context is required');
});
